src/Echantillon/EchantillonBundle/Entity/Echantillon.php
<?php

namespace Echantillon\EchantillonBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Echantillon
 *
 * @ORM\Table(name="echantillon")
 * @ORM\Entity(repositoryClass="Echantillon\EchantillonBundle\Repository\EchantillonRepository")
 */
class Echantillon
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Nom", type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="ReferenceLacapa", type="string", length=255, unique=true)
     */
    private $referenceLacapa;

    /**
     * @var string
     *
     * @ORM\Column(name="ReferenceClient", type="string", length=255, nullable=true)
     */
    private $referenceClient;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateArriv", type="datetime")
     */
    private $dateArriv;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateBut", type="datetime")
     */
    private $dateBut;

    /**
     * @var string
     *
     * @ORM\Column(name="Commentaire", type="blob", nullable=true)
     */
    private $commentaire;

    /**
     * @var bool
     *
     * @ORM\Column(name="Urgent", type="boolean")
     */
    private $urgent;

    /**
     * @var string
     *
     * @ORM\Column(name="Poids", type="string", length=255, nullable=true)
     */
    private $poids;

    /**
     * @var bool
     *
     * @ORM\Column(name="Imprime", type="boolean")
     */
    private $imprime;

    /**
     * @var bool
     *
     * @ORM\Column(name="Supp", type="boolean")
     */
    private $supp;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateSupp", type="datetime", nullable=true)
     */
    private $dateSupp;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateCreation", type="datetime")
     */
    private $dateCreation;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DateModif", type="datetime", nullable=true)
     */
    private $dateModif;

    /**
     * @ORM\ManyToOne(targetEntity="Client\ClientBundle\Entity\Client", inversedBy="echantillons")
     */
    private $client;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="Echantillon\EchantillonBundle\Entity\MoleculesEchantillon", mappedBy="echantillon", cascade={"persist", "remove"})
     */
    private $moleculesEchantillon;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Echantillon
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set dateArriv
     *
     * @param \DateTime $dateArriv
     *
     * @return Echantillon
     */
    public function setDateArriv($dateArriv)
    {
        $this->dateArriv = $dateArriv;

        return $this;
    }

    /**
     * Get dateArriv
     *
     * @return \DateTime
     */
    public function getDateArriv()
    {
        return $this->dateArriv;
    }

    /**
     * Set dateBut
     *
     * @param \DateTime $dateBut
     *
     * @return Echantillon
     */
    public function setDateBut($dateBut)
    {
        $this->dateBut = $dateBut;

        return $this;
    }

    /**
     * Get dateBut
     *
     * @return \DateTime
     */
    public function getDateBut()
    {
        return $this->dateBut;
    }

    /**
     * Set urgent
     *
     * @param boolean $urgent
     *
     * @return Echantillon
     */
    public function setUrgent($urgent)
    {
        $this->urgent = $urgent;

        return $this;
    }

    /**
     * Get urgent
     *
     * @return bool
     */
    public function getUrgent()
    {
        return $this->urgent;
    }

    /**
     * Set poids
     *
     * @param string $poids
     *
     * @return Echantillon
     */
    public function setPoids($poids)
    {
        $this->poids = $poids;

        return $this;
    }

    /**
     * Get poids
     *
     * @return string
     */
    public function getPoids()
    {
        return $this->poids;
    }

    /**
     * Set imprime
     *
     * @param boolean $imprime
     *
     * @return Echantillon
     */
    public function setImprime($imprime)
    {
        $this->imprime = $imprime;

        return $this;
    }

    /**
     * Get imprime
     *
     * @return bool
     */
    public function getImprime()
    {
        return $this->imprime;
    }

    /**
     * Set supp
     *
     * @param boolean $supp
     *
     * @return Echantillon
     */
    public function setSupp($supp)
    {
        $this->supp = $supp;

        return $this;
    }

    /**
     * Get supp
     *
     * @return bool
     */
    public function getSupp()
    {
        return $this->supp;
    }

    /**
     * Set dateSupp
     *
     * @param \DateTime $dateSupp
     *
     * @return Echantillon
     */
    public function setDateSupp($dateSupp)
    {
        $this->dateSupp = $dateSupp;

        return $this;
    }

    /**
     * Get dateSupp
     *
     * @return \DateTime
     */
    public function getDateSupp()
    {
        return $this->dateSupp;
    }

    /**
     * Set dateCreation
     *
     * @param \DateTime $dateCreation
     *
     * @return Echantillon
     */
    public function setDateCreation($dateCreation)
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    /**
     * Get dateCreation
     *
     * @return \DateTime
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }

    /**
     * Set dateModif
     *
     * @param \DateTime $dateModif
     *
     * @return Echantillon
     */
    public function setDateModif($dateModif)
    {
        $this->dateModif = $dateModif;

        return $this;
    }

    /**
     * Get dateModif
     *
     * @return \DateTime
     */
    public function getDateModif()
    {
        return $this->dateModif;
    }

    /**
     * Set client
     *
     * @param \Client\ClientBundle\Entity\Client $client
     *
     * @return Echantillon
     */
    public function setClient(\Client\ClientBundle\Entity\Client $client = null)
    {
        $this->client = $client;

        return $this;
    }

    /**
     * Get client
     *
     * @return \Client\ClientBundle\Entity\Client
     */
    public function getClient()
    {
        return $this->client;
    }


    /**
     * Set referenceClient
     *
     * @param string $referenceClient
     *
     * @return Echantillon
     */
    public function setReferenceClient($referenceClient)
    {
        $this->referenceClient = $referenceClient;

        return $this;
    }

    /**
     * Get referenceClient
     *
     * @return string
     */
    public function getReferenceClient()
    {
        return $this->referenceClient;
    }

    /**
     * Set commentaire
     *
     * @param string $commentaire
     *
     * @return Echantillon
     */
    public function setCommentaire($commentaire)
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * Get commentaire
     *
     * @return string
     */
    public function getCommentaire()
    {
        if(!empty($this->commentaire)){
            return stream_get_contents($this->commentaire);
        }else {
            return "";
        }
    }

    /**
     * Set referenceLacapa
     *
     * @param string $referenceLacapa
     *
     * @return Echantillon
     */
    public function setReferenceLacapa($referenceLacapa)
    {
        $this->referenceLacapa = $referenceLacapa;

        return $this;
    }

    /**
     * Get referenceLacapa
     *
     * @return string
     */
    public function getReferenceLacapa()
    {
        return $this->referenceLacapa;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->moleculesEchantillon = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add moleculesEchantillon
     *
     * @param \Echantillon\EchantillonBundle\Entity\MoleculesEchantillon $moleculesEchantillon
     *
     * @return Echantillon
     */
    public function addMoleculesEchantillon(\Echantillon\EchantillonBundle\Entity\MoleculesEchantillon $moleculesEchantillon)
    {
        $this->moleculesEchantillon[] = $moleculesEchantillon;

        return $this;
    }

    /**
     * Remove moleculesEchantillon
     *
     * @param \Echantillon\EchantillonBundle\Entity\MoleculesEchantillon $moleculesEchantillon
     */
    public function removeMoleculesEchantillon(\Echantillon\EchantillonBundle\Entity\MoleculesEchantillon $moleculesEchantillon)
    {
        $this->moleculesEchantillon->removeElement($moleculesEchantillon);
    }

    /**
     * Get moleculesEchantillon
     *
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getMoleculesEchantillon()
    {
        return $this->moleculesEchantillon;
    }

    /**
     * Get nbNotAnalyse
     * @return int
     */
    public function nbNotAnalyse(){
        $count = 0;
        foreach ($this->moleculesEchantillon as $row){
            if($row->getIsAnalyse() === false){
                $count ++;
            }
        }
        return $count;
    }

    /**
     * Get nbAnalyse
     * @return int
     */
    public function nbAnalyse(){
        $count = 0;
        foreach ($this->moleculesEchantillon as $row){
            if($row->getIsAnalyse() === true){
                $count ++;
            }
        }
        return $count;
    }

    /**
     * @return mixed
     */
    public function getDateAnalyse(){
        $datas = [];

src/Echantillon/EchantillonBundle/Resources/views/Default/echantillon_fiche.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/af-2.2.0/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/datatables.min.css"/>
{% endblock %}
{% block body %}
    <h1>Fiche de l'échantillon {{ echantillon.referenceLacapa }}</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ path("utilisateurs_homepage") }}">Accueil</a>
        </li>
        <li>
            <a href="{{ path('echantillon_homepage') }}">Liste échantillons</a>
        </li>
        <li class="active">
            Fiche échantillon
        </li>
    </ol>
    <div class="row">
        <div class="col-md-6">
            <label>Date d'arrivée :</label> {{ echantillon.dateArriv | date("d/m/Y H:i:s") }} <br>
            <label>Date butoir :</label> {{ echantillon.dateBut | date("d/m/Y") }}
        </div>
        <div class="col-md-6 text-right">
            <label>Date de création :</label> {{ echantillon.dateCreation | date("d/m/Y H:i:s") }} <br>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <dl class="dl-horizontal" id="clientFiche">
                    <dt>Nom :</dt>
                    <dd>{{ echantillon.nom }}</dd>
                    <dt>Client :</dt>
                    <dd><a href="{{ path('client_fiche', {id : echantillon.client.id}) }}">{{ echantillon.client.nom }}</a></dd>
                    <dt>Reférence Client : </dt>
                    <dd>{{ echantillon.referenceClient }}</dd>
                    <dt>Commentaire : </dt>
                    <dd>{{ echantillon.commentaire }}</dd>
                    <dt>Urgent : </dt>
                    <dd>
                        {% if echantillon.urgent %}
                            Oui
                        {% else %}
                            Non
                        {% endif %}
                    </dd>
                    <dt>Poids</dt>
                    <dd>{{ echantillon.poids }}</dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Liste des molécules pour cette échantillon</h3>
            <div class="row">
                <div class="col-md-5">
                    <select class="form-control" id="displaySelection">
                        <option {% if mode != 'detected' %} selected="selected" {% endif %} value="all">Tous afficher</option>
                        <option {% if mode == 'detected' %} selected="selected" {% endif %} value="detected">Afficher les détectés</option>
                    </select>
                </div>
            </div>
            <br>
            <div class="well">
                {% for familleDatas in moleculesEchantillon %}
                    <div class="row">
                        <div class="col-md-6"><h2 id="{{ familleDatas.famille }}">Famille {{ familleDatas.famille }}</h2></div>
                        <div class="col-md-6 text-right">
                            <label>Familles :</label> <br>
                            {% for familleData in moleculesEchantillon %}
                                <a href="#{{ familleData.famille }}" class="btn btn-primary btn-xs">{{ familleData.famille }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Ref. Lacapa</th>
                                    <th>Résultats</th>
                                    <th>Taux Récup. (%)</th>
                                    <th>Unité</th>
                                    <th>Date Analyse</th>
                                    <th>Remarque</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for row in familleDatas.echantillons %}
                                    <tr>
                                        <td>{{ (row|first).molecules.nom }}</td>
                                        <td>{{ (row|first).resulat }}</td>
                                        <td>{{ (row|first).tauxRecup }}</td>
                                        <td>{{ row.unite }}</td>
                                        <td>
                                            {% if familleDatas.paillasse %}
                                                {{ familleDatas.paillasse.dateCreation | date('d/m/Y') }}
                                            {% endif %}
                                        </td>
                                        <td>{{ (row|first).commentaire }}</td>
                                        <td><button class="btn btn-primary btnClip" data-clipboard-text="{{ (row|first).molecules.nom }} : {{ (row|first).resulat }} {{ row.unite }}" data-toggle="tooltip" data-placement="right" title="Copié !"><i class="fa fa-clipboard" aria-hidden="true"></i></button></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
                {#<table class="table table-striped" id="modele_table">
                    <thead>
                    <tr>
                        <th>FAMILLE</th>
                        <th>NOM</th>
                        <th>RESULTAT</th>
                        <th>COMMENTAIRE
                        <th>DATE ANALYSE</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for molecule in moleculesEchantillon %}
                        <tr>
                            <td>{{ molecule.molecules.famille.nom }}</td>
                            <td>{{ molecule.molecules.nom }}</td>
                            <td>
                                {% if molecule.isAnalyse == 0 %}
                                    <span class="text-danger">en attente</span>
                                {% endif %}
                                {% if molecule.isAnalyse == 1 %}
                                    {% if molecule.resulat == "No" %}
                                        < LQ
                                        {% else %}
                                        {{ molecule.resulat }}  {{ molecule.molecules.methodes.first.unite }}
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td>{{ molecule.commentaire }}</td>
                            <td>{{ molecule.dateAnalyse | date("d/m-Y H:i:s") }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>#}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/af-2.2.0/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/datatables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/plug-ins/1.10.15/sorting/date-euro.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
    <script>
        $(function() {

            $("#displaySelection").on("change", function () {
                var modeVal = $(this).val();
                window.location = Routing.generate("echantillon_fiche", {id : {{ echantillon.id}}, mode : modeVal});
            });

            $('.btnClip').tooltip({
                trigger: 'click',
                placement: 'right'
            });

            function setTooltip(message) {
                $('btnClip').tooltip('hide')
                    .attr('data-original-title', message)
                    .tooltip('show');
            }

            function hideTooltip() {
                setTimeout(function() {
                    $('.btnClip').tooltip('hide');
                }, 1000);
            }


            var clipboard = new Clipboard('.btnClip');

            clipboard.on('success', function(e) {
                setTooltip('Copié !');
                hideTooltip();
            });


            new Clipboard(".btnClip");

            $(".btnClip").click(function(){
               $(this).tooltip("show");
            });

            $("#modele_table").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/French.json"
                }
            });
        });
    </script>
{% endblock %}

src/Echantillon/EchantillonBundle/Resources/views/Default/echantillon_print_echantillons.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        .item{
            margin-top: 0;

        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="hidden-print">
            <a href="{{ url('echantillon_print_list') }}">Retour à la liste</a>
            <br><br>
            <a href="#" class="btn btn-primary printButton hidden-print">Imprimer</a>
            <hr>
        </div>
        <div class="row">
            {% for echantillon in listEchantillons %}
                <div class="col-xs-6 item">
                    <p class="text-center" style="font-size: 1.4em;"><strong>{{ echantillon.echantillon.referenceLacapa }}</strong></p>
                    <p>{{ echantillon.echantillon.client.nom }}</p>
                    <p>{{ echantillon.familles | join(',') }}</p>
                    <p>Recu le :    {{ echantillon.echantillon.dateArriv | date("d/m/Y H:i") }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $(".printButton").click(function(){
            window.print();
        });
    })
</script>
</html>

src/Echantillon/EchantillonBundle/Resources/views/Default/echantillon_print_list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Outil Etiquette</h1>
    <div class="well">
        <h2>Échantillon à imprimer</h2>
        <div class="row">
            {% if app.request.attributes.get("_route") == 'echantillon_print_list' %}
                <div class="col-md-12">
                    <a href="{{ path('echntillon_print_cancel_list') }}" class="btn btn-primary btn-sm">Réinitialiser etiquettes</a>
                </div>
                {% else %}
                    <div class="col-md-12">
                        <a href="{{ path('echantillon_print_list') }}" class="btn btn-primary btn-sm">Imprimer des étiquettes</a>
                    </div>
            {% endif %}
            <div class="col-md-6">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="CheckThemAll"> Tout sélectionner
                    </label>
                </div>
            </div>
        </div>
        <form action="{% if app.request.attributes.get("_route") == "echntillon_print_cancel_list" %} {{ path('echntillon_print_cancel_list') }}  {% else %} {{ url('echantillon_print_echantillons') }}{% endif %}" method="post" {% if app.request.attributes.get("_route") == "echantillon_print_list" %} target="_blank" {% endif %}>
            <button type="submit" class="btn btn-primary submitButton">Valider</button>
            <br><br>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>REF. LACAPA</th>
                        <th>NOM</th>
                        <th>REF CLIENT</th>
                        <th>IMPRIME</th>
                    </tr>
                </thead>
                <tbody>

                        {% for echantillon in listEchantillon %}
                            <tr>
                                <td>{{ echantillon.referenceLacapa }}</td>
                                <td>{{ echantillon.nom }}</td>
                                <td>{{ echantillon.referenceClient }}</td>
                                <td>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="checkBox" name="echantillon[]" value="{{ echantillon.id }}">
                                            {% if echantillon.imprime %}
                                                    Réinitialise l'impression
                                                {% else %}
                                                    Imprimer
                                            {% endif %}
                                        </label>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                </tbody>
            </table>
            <button type="submit" id="" class="btn btn-primary submitButton">Valider</button>
        </form>
    </div>
{% endblock %}
{% block javascripts %}
    <script>

        $("#CheckThemAll").on("change", function () {
          if ($(this).is(":checked")){
              $(".checkBox").prop("checked", true);
          }else {
              $(".checkBox").prop("checked", false);
          }
        });

        var reloadFunction = function(){
            location.reload(true);
            console.log("reload trigger");
        };

        $(document).ready(function () {

            $(".submitButton").click(function () {
                setTimeout(reloadFunction, 4000);
            })
        })
    </script>
{% endblock %}

src/Echantillon/EchantillonBundle/Resources/views/Default/index.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/af-2.2.0/b-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/datatables.min.css"/>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1>Liste des échantillons</h1>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path("utilisateurs_homepage") }}">Accueil</a>
                </li>
                <li class="active">
                    Liste échantillons
                </li>
            </ol>
        </div>
        <div class="col-md-12">
            <a href="{{ path('echantillon_add') }}" class="btn btn-primary btn-sm">Ajouter un échantillon</a>
            <br><br>
            <div class="well">
                <table class="table table-striped" id="listEchantillon">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>REF. LACAPA</th>
                        <th>REF. ECHAN.</th>
                        <th>Nom Échantillon</th>
                        <th>CLIENT</th>
                        <th>ANNULE</th>
                        <th>ACTIONS</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for echantillon in listEchantillon %}
                        <tr {% if echantillon.supp %}class="danger" {% endif %}>
                            <td style="opacity: .3;">{{ echantillon.id }}</td>
                            <td style="font-weight: bold;">{{ echantillon.referenceLacapa }} {{ echantillon.urgent ? '<span class="label label-info">Urgent</span>' : ''}}</td>
                            <td>{{ echantillon.referenceClient }}</td>
                            <td>{{ echantillon.nom }}</td>
                            <td><a href="{{ path('client_fiche', { id : echantillon.client.id}) }}">{{ echantillon.client.abrege }}</a></td>
                            <td>
                                {% if echantillon.supp %}
                                    ANNULÉ
                                {% endif %}
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Action <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ path('echantillon_fiche', {id : echantillon.id}) }}">Voir</a></li>
                                        {% if is_granted("ROLE_ADMINISTRATIF") or is_granted('ROLE_RES_TECH')%}
                                            <li><a href="{{ path('echantillon_update', {id : echantillon.id}) }}">Modifier les informations</a></li>
                                            <li><a href="{{ path('echantillon_update_molecules', {id : echantillon.id}) }}">Modifier les molécules</a></li>
                                            <li role="separator" class="divider"></li>
                                            {% if echantillon.supp %}
                                                    <li><a href="{{ path('echantillon_undelete', {id : echantillon.id}) }}">Remettre</a></li>
                                                {% else %}
                                                    <li><a href="{{ path('echantillon_delete', {id : echantillon.id}) }}">Annuler</a></li>
                                            {% endif %}

                                        {% endif %}
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/af-2.2.0/b-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/datatables.min.js"></script>
    <script>
        $( document ).ready(function() {
            $("#listEchantillon").DataTable({
                "iDisplayLength" : 50,
                'order' : [0, 'desc'],
                /*"columnDefs": [
                    { type: 'date-euro', targets: [3,4] }
                ],
                colReorder: true,*/
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/French.json"
                }
            });
        });
    </script>
{% endblock %}